### ISSUE TITLE
Typo in PKGBUILD for trusted GPG keys

### ISSUE THREAD

**Issue by vsund** [hv15/plex-media-player-standalone-service#1]
Hey there, first of all thank you very much for providing this package (saves me quite some work :)).

I noticed that you've added `validgpgkeys` to your PKGBUILD (so that users don't need to manually add your key). I don't know whether this changed lately (and I'm really not into packaging), but it seems like this option is `validpgpkeys` instead of `validgpgkeys` (`gpg` vs `pgp`).

After replacing this option, everything installed great without needing to manually trust your key.

**Comment by hv15** [comment]
Thanks @vsund for noticing this! I can't believe I made this mistake, and that it went unnoticed for 3 years. I've updated the AUR repo now, the output of `makepkg --printsrcinfo` now actually includes my fingerprint.
